import type { ResourceConfig } from "../types/admin";

const genderOptions = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
  { label: "Mix", value: "mix" },
];

const activeOptions = [
  { label: "Active", value: "active" },
  { label: "Inactive", value: "inactive" },
];

export const resourceConfigs: ResourceConfig[] = [
  {
    key: "settings",
    title: "Web Settings",
    description: "Pengaturan global untuk identitas situs, SEO, kontak, dan aset utama.",
    group: "content",
    endpoint: "admin/settings",
    columns: [
      { key: "site_name", label: "Site" },
      { key: "site_url", label: "URL" },
      { key: "email", label: "Email" },
      { key: "updated_at", label: "Diperbarui", format: "datetime" },
    ],
    fields: [
      { key: "site_name", label: "Site name", type: "text", required: true },
      { key: "site_url", label: "Site URL", type: "url", required: true },
      { key: "tagline", label: "Tagline", type: "text" },
      { key: "email", label: "Email", type: "email" },
      { key: "phone_number", label: "Phone", type: "text" },
      { key: "whatsapp_number", label: "WhatsApp number", type: "text" },
      { key: "address", label: "Address", type: "textarea", rows: 3 },
      { key: "author_name", label: "Author name", type: "text" },
      { key: "author_url", label: "Author URL", type: "url" },
      { key: "facebook_url", label: "Facebook URL", type: "url" },
      { key: "instagram_url", label: "Instagram URL", type: "url" },
      { key: "discord_url", label: "Discord URL", type: "url" },
      { key: "whatsapp_url", label: "WhatsApp URL", type: "url" },
      { key: "about_description", label: "About description", type: "textarea", rows: 4 },
      { key: "about_image_alt", label: "About image alt", type: "text" },
      { key: "about_image_path", label: "About image", type: "file", accept: "image/*" },
      { key: "logo_path", label: "Logo", type: "file", accept: "image/*" },
      { key: "favicon_path", label: "Favicon", type: "file", accept: "image/*" },
      { key: "meta_title", label: "Meta title", type: "text" },
      { key: "meta_description", label: "Meta description", type: "textarea", rows: 3 },
      { key: "meta_keywords", label: "Meta keywords", type: "text" },
    ],
  },
  {
    key: "menus",
    title: "Menus",
    description: "Navigasi utama dan footer yang dipakai frontend publik.",
    group: "content",
    endpoint: "admin/menus",
    columns: [
      { key: "title", label: "Judul" },
      { key: "url", label: "URL" },
      { key: "parent_id", label: "Parent" },
      { key: "order", label: "Urutan" },
    ],
    fields: [
      {
        key: "parent_id",
        label: "Parent menu",
        type: "select",
        optionSource: { resourceKey: "menus", labelField: "title", valueField: "id" },
      },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "url", label: "URL", type: "url" },
      { key: "order", label: "Order", type: "number", required: true },
    ],
  },
  {
    key: "headers",
    title: "Hero Headers",
    description: "Slide hero dan video pembuka halaman utama.",
    group: "content",
    endpoint: "admin/headers",
    columns: [
      { key: "title", label: "Judul" },
      { key: "subtitle", label: "Subjudul" },
      { key: "video_url", label: "Video URL" },
      { key: "updated_at", label: "Diperbarui", format: "datetime" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "subtitle", label: "Subtitle", type: "textarea", rows: 3 },
      { key: "image_alt", label: "Image alt", type: "text" },
      { key: "video_url", label: "Video URL", type: "url" },
      { key: "image", label: "Image", type: "file", accept: "image/*" },
    ],
  },
  {
    key: "categories",
    title: "Categories",
    description: "Kategori artikel dan konten lain yang dipakai frontend.",
    group: "content",
    endpoint: "admin/categories",
    columns: [
      { key: "title", label: "Nama" },
      { key: "slug", label: "Slug" },
      { key: "status", label: "Status" },
      { key: "updated_at", label: "Diperbarui", format: "datetime" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "url", label: "URL", type: "url" },
      { key: "status", label: "Status", type: "select", required: true, options: activeOptions },
    ],
  },
  {
    key: "tags",
    title: "Tags",
    description: "Tag artikel, produk, dan streaming.",
    group: "content",
    endpoint: "admin/tags",
    columns: [
      { key: "title", label: "Tag" },
      { key: "slug", label: "Slug" },
      { key: "updated_at", label: "Diperbarui", format: "datetime" },
    ],
    fields: [{ key: "title", label: "Title", type: "text", required: true }],
  },
  {
    key: "blogs",
    title: "Blogs",
    description: "Artikel yang tampil pada halaman berita publik.",
    group: "content",
    endpoint: "admin/blogs",
    columns: [
      { key: "title", label: "Judul" },
      { key: "category_id", label: "Kategori" },
      { key: "user_id", label: "Author" },
      { key: "created_at", label: "Dibuat", format: "datetime" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "content", label: "Content", type: "textarea", required: true, rows: 8 },
      {
        key: "category_id",
        label: "Category",
        type: "select",
        required: true,
        optionSource: { resourceKey: "categories", labelField: "title", valueField: "id" },
      },
      {
        key: "tag",
        label: "Tags",
        type: "multiselect",
        optionSource: { resourceKey: "tags", labelField: "title", valueField: "id" },
      },
      { key: "image_alt", label: "Image alt", type: "text" },
      { key: "image", label: "Image", type: "file", accept: "image/*" },
    ],
  },
  {
    key: "subscribes",
    title: "Subscribers",
    description: "Daftar newsletter yang terhubung dengan form subscribe di website.",
    group: "content",
    endpoint: "admin/subscribes",
    columns: [
      { key: "email", label: "Email" },
      { key: "is_subscribed", label: "Aktif", format: "boolean" },
      { key: "updated_at", label: "Diperbarui", format: "datetime" },
    ],
    fields: [
      { key: "email", label: "Email", type: "email", required: true },
      { key: "is_subscribed", label: "Subscribed", type: "checkbox" },
    ],
  },
  {
    key: "usefulls",
    title: "Useful Links",
    description: "Link tambahan untuk footer dan halaman bantuan.",
    group: "content",
    endpoint: "admin/usefulls",
    columns: [
      { key: "title", label: "Judul" },
      { key: "slug", label: "Slug" },
      { key: "url", label: "URL" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text" },
      { key: "url", label: "URL", type: "url" },
    ],
  },
  {
    key: "tarkams",
    title: "Tarkams",
    description: "Master data event/tarkam yang menjadi inti halaman kompetisi.",
    group: "competition",
    endpoint: "admin/tarkams",
    columns: [
      { key: "week", label: "Week" },
      { key: "title", label: "Judul" },
      { key: "status", label: "Status" },
      { key: "location", label: "Lokasi" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "week", label: "Week", type: "text", required: true },
      { key: "status", label: "Status", type: "text" },
      { key: "description", label: "Description", type: "textarea", rows: 5 },
      { key: "transfer_info", label: "Transfer info", type: "textarea", rows: 3 },
      { key: "proof", label: "Proof", type: "text" },
      { key: "thumbnail", label: "Thumbnail URL", type: "url" },
      { key: "image", label: "Image URL", type: "url" },
      { key: "pool_price_m", label: "Pool price male", type: "number" },
      { key: "pool_price_f", label: "Pool price female", type: "number" },
      { key: "male_date", label: "Male date", type: "date" },
      { key: "male_time", label: "Male time", type: "text" },
      { key: "female_date", label: "Female date", type: "date" },
      { key: "female_time", label: "Female time", type: "text" },
      { key: "male_slot", label: "Male slot", type: "number" },
      { key: "female_slot", label: "Female slot", type: "number" },
      { key: "male_completed", label: "Male completed", type: "number" },
      { key: "female_completed", label: "Female completed", type: "number" },
      { key: "mvp_m", label: "MVP male", type: "text" },
      { key: "mvp_f", label: "MVP female", type: "text" },
      { key: "location", label: "Location", type: "text" },
    ],
  },
  {
    key: "clubs",
    title: "Clubs",
    description: "Identitas klub komunitas yang tampil pada halaman klub.",
    group: "competition",
    endpoint: "admin/clubs",
    identifierField: "code",
    columns: [
      { key: "code", label: "Kode" },
      { key: "name", label: "Nama" },
      { key: "level", label: "Level" },
      { key: "points", label: "Poin" },
    ],
    fields: [
      { key: "code", label: "Code", type: "text", required: true },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "logo", label: "Logo URL", type: "url" },
      { key: "level", label: "Level", type: "text" },
      { key: "points", label: "Points", type: "number" },
      { key: "facebook", label: "Facebook URL", type: "url" },
      { key: "instagram", label: "Instagram URL", type: "url" },
      { key: "tiktok", label: "TikTok URL", type: "url" },
    ],
  },
  {
    key: "members",
    title: "Members",
    description: "Roster komunitas yang dipakai player, sponsor, dan profil member.",
    group: "competition",
    endpoint: "admin/members",
    identifierField: "nickname",
    columns: [
      { key: "nickname", label: "Nickname" },
      { key: "gender", label: "Gender" },
      { key: "city", label: "Kota" },
      { key: "points", label: "Poin" },
    ],
    fields: [
      { key: "username", label: "Username", type: "text" },
      { key: "nickname", label: "Nickname", type: "text", required: true },
      { key: "gender", label: "Gender", type: "select", required: true, options: genderOptions },
      { key: "discord_user_id", label: "Discord user ID", type: "text" },
      { key: "phone_number", label: "Phone number", type: "text" },
      { key: "tunisia_phone", label: "Tunisia phone", type: "text" },
      { key: "city", label: "City", type: "text" },
      { key: "picture_url", label: "Picture URL", type: "url" },
      { key: "tier", label: "Tier", type: "text" },
      {
        key: "club_fk",
        label: "Club",
        type: "select",
        optionSource: { resourceKey: "clubs", labelField: "name", valueField: "id" },
      },
      { key: "wins", label: "Wins", type: "number" },
      { key: "losses", label: "Losses", type: "number" },
      { key: "t_matches", label: "Total matches", type: "number" },
      { key: "points", label: "Points", type: "number" },
      { key: "status", label: "Status", type: "text" },
      { key: "facebook", label: "Facebook URL", type: "url" },
      { key: "instagram", label: "Instagram URL", type: "url" },
      { key: "tiktok", label: "TikTok URL", type: "url" },
      { key: "latitude", label: "Latitude", type: "number" },
      { key: "longitude", label: "Longitude", type: "number" },
    ],
  },
  {
    key: "players",
    title: "Players",
    description: "Pendaftaran player pada tiap season/tarkam.",
    group: "competition",
    endpoint: "admin/players",
    columns: [
      { key: "member.nickname", label: "Member" },
      { key: "tarkam.week", label: "Tarkam" },
      { key: "score", label: "Score" },
      { key: "paid", label: "Paid", format: "boolean" },
    ],
    fields: [
      {
        key: "member_fk",
        label: "Member",
        type: "select",
        optionSource: { resourceKey: "members", labelField: "nickname", valueField: "id" },
      },
      {
        key: "tarkam_fk",
        label: "Tarkam",
        type: "select",
        optionSource: { resourceKey: "tarkams", labelField: "week", valueField: "id" },
      },
      { key: "score", label: "Score", type: "number" },
      { key: "paid", label: "Paid", type: "checkbox" },
    ],
  },
  {
    key: "groups",
    title: "Groups",
    description: "Grup peserta berdasarkan kategori gender dan season.",
    group: "competition",
    endpoint: "admin/groups",
    columns: [
      { key: "name", label: "Nama" },
      { key: "gender", label: "Gender" },
      { key: "tarkam.week", label: "Tarkam" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "gender", label: "Gender", type: "select", required: true, options: genderOptions },
      {
        key: "tarkam_fk",
        label: "Tarkam",
        type: "select",
        optionSource: { resourceKey: "tarkams", labelField: "week", valueField: "id" },
      },
    ],
  },
  {
    key: "teams",
    title: "Teams",
    description: "Komposisi tim yang bertanding pada season tertentu.",
    group: "competition",
    endpoint: "admin/teams",
    columns: [
      { key: "name", label: "Nama tim" },
      { key: "gender", label: "Gender" },
      { key: "group.name", label: "Group" },
      { key: "tarkam.week", label: "Tarkam" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "gender", label: "Gender", type: "select", required: true, options: genderOptions },
      {
        key: "member1_fk",
        label: "Member 1",
        type: "select",
        optionSource: { resourceKey: "members", labelField: "nickname", valueField: "id" },
      },
      {
        key: "member2_fk",
        label: "Member 2",
        type: "select",
        optionSource: { resourceKey: "members", labelField: "nickname", valueField: "id" },
      },
      {
        key: "member3_fk",
        label: "Member 3",
        type: "select",
        optionSource: { resourceKey: "members", labelField: "nickname", valueField: "id" },
      },
      {
        key: "group_fk",
        label: "Group",
        type: "select",
        optionSource: { resourceKey: "groups", labelField: "name", valueField: "id" },
      },
      {
        key: "tarkam_fk",
        label: "Tarkam",
        type: "select",
        optionSource: { resourceKey: "tarkams", labelField: "week", valueField: "id" },
      },
      { key: "date", label: "Date", type: "date" },
      { key: "time", label: "Time", type: "text" },
    ],
  },
  {
    key: "contests",
    title: "Contests",
    description: "Bracket pertandingan, lawan, dan pemenang.",
    group: "competition",
    endpoint: "admin/contests",
    columns: [
      { key: "team1_fk", label: "Team 1" },
      { key: "team2_fk", label: "Team 2" },
      { key: "winner_team_fk", label: "Winner" },
      { key: "score", label: "Score" },
    ],
    fields: [
      {
        key: "team1_fk",
        label: "Team 1",
        type: "select",
        optionSource: { resourceKey: "teams", labelField: "name", valueField: "id" },
      },
      {
        key: "team2_fk",
        label: "Team 2",
        type: "select",
        optionSource: { resourceKey: "teams", labelField: "name", valueField: "id" },
      },
      {
        key: "winner_team_fk",
        label: "Winner team",
        type: "select",
        optionSource: { resourceKey: "teams", labelField: "name", valueField: "id" },
      },
      { key: "score", label: "Score", type: "number" },
      {
        key: "tarkam_fk",
        label: "Tarkam",
        type: "select",
        optionSource: { resourceKey: "tarkams", labelField: "week", valueField: "id" },
      },
      { key: "gender", label: "Gender", type: "select", options: genderOptions },
    ],
  },
  {
    key: "winners",
    title: "Winners",
    description: "Daftar juara dan hadiah pada tiap season.",
    group: "competition",
    endpoint: "admin/winners",
    columns: [
      { key: "nickname", label: "Nickname" },
      { key: "gender", label: "Gender" },
      { key: "prize", label: "Prize" },
      { key: "team_fk", label: "Team" },
    ],
    fields: [
      { key: "nickname", label: "Nickname", type: "text", required: true },
      { key: "gender", label: "Gender", type: "select", required: true, options: genderOptions },
      { key: "prize", label: "Prize", type: "text" },
      {
        key: "team_fk",
        label: "Team",
        type: "select",
        optionSource: { resourceKey: "teams", labelField: "name", valueField: "id" },
      },
      {
        key: "tarkam_fk",
        label: "Tarkam",
        type: "select",
        optionSource: { resourceKey: "tarkams", labelField: "week", valueField: "id" },
      },
    ],
  },
  {
    key: "penyawers",
    title: "Penyawers",
    description: "Supporter/donatur yang terhubung dengan leaderboard dukungan.",
    group: "competition",
    endpoint: "admin/penyawers",
    columns: [
      { key: "name", label: "Nama" },
      { key: "gender", label: "Gender" },
      { key: "amount", label: "Nominal", format: "currency" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "gender", label: "Gender", type: "select", required: true, options: genderOptions },
      { key: "amount", label: "Amount", type: "number", required: true },
      {
        key: "member_fk",
        label: "Member",
        type: "select",
        optionSource: { resourceKey: "members", labelField: "nickname", valueField: "id" },
      },
      {
        key: "tarkam_fk",
        label: "Tarkam",
        type: "select",
        optionSource: { resourceKey: "tarkams", labelField: "week", valueField: "id" },
      },
    ],
  },
  {
    key: "leaderboards",
    title: "Leaderboards",
    description: "Papan peringkat player berdasarkan poin.",
    group: "competition",
    endpoint: "admin/leaderboards",
    columns: [
      { key: "player_fk", label: "Player" },
      { key: "points", label: "Poin" },
      { key: "updated_at", label: "Diperbarui", format: "datetime" },
    ],
    fields: [
      {
        key: "player_fk",
        label: "Player",
        type: "select",
        optionSource: { resourceKey: "players", labelField: "id", valueField: "id" },
      },
      { key: "points", label: "Points", type: "number" },
    ],
  },
  {
    key: "catprods",
    title: "Product Categories",
    description: "Kategori produk toko.",
    group: "commerce",
    endpoint: "admin/catprods",
    columns: [
      { key: "title", label: "Judul" },
      { key: "slug", label: "Slug" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text" },
      { key: "url", label: "URL", type: "url" },
      { key: "status", label: "Status", type: "select", options: activeOptions },
    ],
  },
  {
    key: "products",
    title: "Products",
    description: "Katalog produk yang tampil di shop dan checkout.",
    group: "commerce",
    endpoint: "admin/products",
    columns: [
      { key: "title", label: "Produk" },
      { key: "price", label: "Harga", format: "currency" },
      { key: "status", label: "Status" },
      { key: "catprod.title", label: "Kategori" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text" },
      { key: "sku", label: "SKU", type: "text" },
      { key: "subject", label: "Subject", type: "textarea", rows: 3 },
      { key: "description", label: "Description", type: "textarea", rows: 5 },
      { key: "additional_info", label: "Additional info", type: "textarea", rows: 4 },
      { key: "price", label: "Price", type: "number" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { label: "In Stock", value: "In Stock" },
          { label: "Sold Out", value: "Sold Out" },
        ],
      },
      {
        key: "catprod_id",
        label: "Category",
        type: "select",
        required: true,
        optionSource: { resourceKey: "catprods", labelField: "title", valueField: "id" },
      },
      {
        key: "user_id",
        label: "User",
        type: "select",
        required: true,
        optionSource: { resourceKey: "users", labelField: "name", valueField: "id" },
      },
    ],
  },
  {
    key: "thumbnails",
    title: "Thumbnails",
    description: "Thumbnail produk yang dapat dipakai pada listing toko.",
    group: "commerce",
    endpoint: "admin/thumbnails",
    columns: [
      { key: "title", label: "Judul" },
      { key: "product_thumbnail_path", label: "Path" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "product_thumbnail_path", label: "Image path", type: "text" },
    ],
  },
  {
    key: "streamings",
    title: "Streamings",
    description: "Konten live dan video streaming pada halaman sponsor/stream.",
    group: "commerce",
    endpoint: "admin/streamings",
    columns: [
      { key: "title", label: "Judul" },
      { key: "url", label: "URL" },
      { key: "tarkam.week", label: "Tarkam" },
      { key: "user_id", label: "User" },
      { key: "updated_at", label: "Diperbarui", format: "datetime" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text" },
      { key: "url", label: "URL", type: "url", required: true },
      { key: "embed", label: "Embed code", type: "textarea", rows: 4 },
      { key: "description", label: "Description", type: "textarea", rows: 4 },
      {
        key: "user_id",
        label: "User",
        type: "select",
        required: true,
        optionSource: { resourceKey: "users", labelField: "name", valueField: "id" },
      },
      {
        key: "tarkam_fk",
        label: "Tarkam",
        type: "select",
        required: true,
        optionSource: { resourceKey: "tarkams", labelField: "week", valueField: "id" },
      },
      { key: "thumbnail", label: "Thumbnail", type: "file", accept: "image/*" },
    ],
  },
  {
    key: "carts",
    title: "Carts",
    description: "Data keranjang pengguna untuk checkout.",
    group: "commerce",
    endpoint: "admin/carts",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "product.title", label: "Produk" },
      { key: "quantity", label: "Qty" },
      { key: "status", label: "Status" },
    ],
  },
  {
    key: "users",
    title: "Users",
    description: "Akun admin/editor yang dipakai mengelola API dan panel.",
    group: "system",
    endpoint: "admin/users",
    columns: [
      { key: "name", label: "Nama" },
      { key: "email", label: "Email" },
      { key: "email_verified_at", label: "Verified", format: "datetime" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "email", label: "Email", type: "email", required: true },
      { key: "password", label: "Password", type: "text", helperText: "Kosongkan saat edit jika tidak ingin mengubah password." },
      { key: "email_verified_at", label: "Verified at", type: "datetime-local" },
    ],
  },
  {
    key: "aliases",
    title: "Aliases",
    description: "Alias member untuk bot dan sinkronisasi data.",
    group: "system",
    endpoint: "admin/aliases",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "alias", label: "Alias" },
      { key: "member_fk", label: "Member" },
    ],
  },
  {
    key: "broadcasts",
    title: "Broadcasts",
    description: "Riwayat broadcast dan pengiriman pesan sistem.",
    group: "system",
    endpoint: "admin/broadcasts",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "title", label: "Judul" },
      { key: "status", label: "Status" },
    ],
  },
  {
    key: "penyawer-leaderboards",
    title: "Penyawer Leaderboards",
    description: "Papan peringkat penyawer dengan identifier berbasis nama.",
    group: "system",
    endpoint: "admin/penyawer-leaderboards",
    identifierField: "name",
    mode: "json",
    columns: [
      { key: "name", label: "Nama" },
      { key: "points", label: "Poin" },
    ],
  },
  {
    key: "sessions",
    title: "Sessions",
    description: "Data sesi dan status permainan.",
    group: "system",
    endpoint: "admin/sessions",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "title", label: "Judul" },
      { key: "status", label: "Status" },
    ],
  },
  {
    key: "timelines",
    title: "Timelines",
    description: "Timeline acara dan aktivitas kompetisi.",
    group: "system",
    endpoint: "admin/timelines",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "title", label: "Judul" },
      { key: "created_at", label: "Dibuat", format: "datetime" },
    ],
  },
  {
    key: "member-timelines",
    title: "Member Timelines",
    description: "Relasi many-to-many antara member dan timeline.",
    group: "system",
    endpoint: "admin/member-timelines",
    readOnly: true,
    mode: "json",
    columns: [
      { key: "member_fk", label: "Member" },
      { key: "timeline_fk", label: "Timeline" },
    ],
  },
  {
    key: "trivias",
    title: "Trivias",
    description: "Data trivia untuk integrasi game/bot.",
    group: "system",
    endpoint: "admin/trivias",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "question", label: "Question" },
    ],
  },
  {
    key: "questions",
    title: "Questions",
    description: "Master pertanyaan untuk modul trivia.",
    group: "system",
    endpoint: "admin/questions",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "question", label: "Question" },
    ],
  },
  {
    key: "question-options",
    title: "Question Options",
    description: "Pilihan jawaban untuk pertanyaan trivia.",
    group: "system",
    endpoint: "admin/question-options",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "question_fk", label: "Question" },
      { key: "is_correct", label: "Benar", format: "boolean" },
    ],
  },
  {
    key: "answers-log",
    title: "Answer Logs",
    description: "Audit jawaban dari user/bot.",
    group: "system",
    endpoint: "admin/answers-log",
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "question_fk", label: "Question" },
      { key: "status", label: "Status" },
    ],
  },
  {
    key: "bot-settings",
    title: "Bot Settings",
    description: "Konfigurasi bot dengan identifier komposit.",
    group: "system",
    endpoint: "admin/bot-settings",
    readOnly: true,
    mode: "json",
    columns: [
      { key: "guild_id", label: "Guild" },
      { key: "key", label: "Key" },
      { key: "value", label: "Value" },
    ],
  },
  {
    key: "whatsapp-messages",
    title: "WhatsApp Messages",
    description: "Riwayat pesan WhatsApp yang masuk ke sistem.",
    group: "system",
    endpoint: "admin/whatsapp-messages",
    readOnly: true,
    mode: "json",
    columns: [
      { key: "id", label: "ID" },
      { key: "sender_name", label: "Sender" },
      { key: "message", label: "Message" },
      { key: "created_at", label: "Dibuat", format: "datetime" },
    ],
  },
];

export const resourceMap = Object.fromEntries(
  resourceConfigs.map((resource) => [resource.key, resource]),
);

export const resourceGroups = [
  {
    key: "content",
    label: "Konten Situs",
    resourceKeys: resourceConfigs
      .filter((resource) => resource.group === "content")
      .map((resource) => resource.key),
  },
  {
    key: "competition",
    label: "Kompetisi",
    resourceKeys: resourceConfigs
      .filter((resource) => resource.group === "competition")
      .map((resource) => resource.key),
  },
  {
    key: "commerce",
    label: "Commerce",
    resourceKeys: resourceConfigs
      .filter((resource) => resource.group === "commerce")
      .map((resource) => resource.key),
  },
  {
    key: "system",
    label: "Sistem",
    resourceKeys: resourceConfigs
      .filter((resource) => resource.group === "system")
      .map((resource) => resource.key),
  },
];
